### ISSUE TITLE
Add facet to histogram

### ISSUE THREAD

**Issue by lvjustice** [mark-andrews/psyntur#2]
It would be useful if we could add facet to the histogram function so that each level of a factor has its own separate plot.

**Comment by mark-andrews** [comment]
Do you mean add faceting in addition to using colour, or as an alternative to using colour? In other words, in the first version, users can colour by one factor and facet by another factor. In the other version, they can choose a single factor, and colour by it or facet by it. I think we should allow colouring by one factor and faceting by another, but the same factor could be used for both colouring and faceting.

It should be noted that faceting is already possible if we use `+ facet_wrap(...)` just like in regular `ggplot`.
For example, this single histogram 
```r
histogram(x = len, data = ToothGrowth)
```
could be faceted by `supp` as follows:
```r
histogram(x = len, data = ToothGrowth) + facet_wrap(~ supp)
```

However, arguably, we are better to avoid falling back on standard `ggplot` commands, and just add a new argument such as `facet = supp`, e.g. 
```r
# won't work as of now (0.0.1)
histogram(x = len, facet = supp, data = ToothGrowth)
```

An important general discussion is where do we draw the line with features for these commands. Obviously, we can consider use cases for additional features that are part of `ggplot`. On the other hand, if we keep implementing them, we end up reinventing the `ggplot` wheel. I think our criterion for including a new feature is whether or not it is necessary for the specific requirements of the introductory statistics classes. If it is not needed for that specific purpose, then we should not implement it and instead advice those who need it to learn `ggplot`, which we want to teach anyway because of its generality. I'm not suggesting the including the facet option is not necessary for these specific purposes. I'm just saying that we can use this as a criterion for deciding on whether to add a new feature or not.

**Comment by lvjustice** [comment]
Yeah the first version where users can colour by one factor and facet by another. I recognise that we have to draw lines between what we implement in the package and what we can draw from `ggplot` but I think asking students to visualise the distribution of individual variables is important. We'll be covering distributions in visualisation, when discussion the normal distribution and again when we teach model evaluation (i.e. dealing with non-normal data) so I think it should be a core feature.
