### ISSUE TITLE
Issue with `describe_across` examples

### ISSUE THREAD

**Issue by jensroes** [mark-andrews/psyntur#41]
The examples for `describe_across` seem to have a mistake (or I'm missing an update).

The examples are like this

```
describe_across(faithfulfaces, 
                variables = c(trustworthy, faithful), 
                functions = list(avg = mean, stdev = sd), 
                by = face_sex)
```

but should be (quotes around function names)

```
describe_across(faithfulfaces, 
                variables = c(trustworthy, faithful), 
                functions = list(avg = "mean", stdev = "sd"), 
                by = face_sex)
```

**Comment by mark-andrews** [comment]
The following works. 
``` r
library(psyntur)
describe_across(faithfulfaces, 
                variables = c(trustworthy, faithful), 
                functions = list(avg = mean, stdev = sd), 
                by = face_sex)
#> # A tibble: 2 × 5
#>   face_sex trustworthy_avg trustworthy_stdev faithful_avg faithful_stdev
#>   <chr>              <dbl>             <dbl>        <dbl>          <dbl>
#> 1 female              4.44             0.742         5.55          0.802
#> 2 male                4.21             0.822         4.75          0.932
```
And, in fact, if it is an example in the help page or a vignette, it *must* work.

Quotes of functions not necessary. Actually, I am surprised that quoted functions work at all.

We are passing in functions, the functions are referred to as, e.g. `mean`, not `"mean"`, though evidently the latter works too.

**Comment by jensroes** [comment]
Okay that must be an update issue cause I get an error when I'm not using quotes but it works when I'm using quotes.

**Comment by mark-andrews** [comment]
I'm not sure which update could make a difference here. The `describe_across` has not changed since the initial version back in September 2020.

What error message are you getting? It would be good to know in case someone else gets it.

On Wed, 2022-02-16 at 12:52 -0800, Jens Roeser wrote:

Okay that must be an update issue cause I get an error when I'm not using quotes but it works when I'm using quotes.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmark-andrews%2Fpsyntur%2Fissues%2F41%23issuecomment-1042300252&data=04%7C01%7Cmark.andrews%40ntu.ac.uk%7C9e7f1d24d5b14fe059fe08d9f18e4c7c%7C8acbc2c5c8ed42c78169ba438a0dbe2f%7C1%7C0%7C637806415782328331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=w%2FIjkFISNu4mv5Nnek2o6%2FXhgEAPjNPNfoMSOf1dp6Y%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAI5GSFMAGQPMUPPHRCBUBB3U3QFCFANCNFSM5OSNLJSQ&data=04%7C01%7Cmark.andrews%40ntu.ac.uk%7C9e7f1d24d5b14fe059fe08d9f18e4c7c%7C8acbc2c5c8ed42c78169ba438a0dbe2f%7C1%7C0%7C637806415782328331%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HzEGO4NdYACtbIfJARrwXZJfHlOSP9zlkia%2BLqO37M0%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

DISCLAIMER: This email is intended solely for the addressee. It may contain private and confidential information. If you are not the intended addressee, please take no action based on it nor show a copy to anyone. In this case, please reply to this email to highlight the error. Opinions and information in this email that do not relate to the official business of Nottingham Trent University shall be understood as neither given nor endorsed by the University. Nottingham Trent University has taken steps to ensure that this email and any attachments are virus-free, but we do advise that the recipient should check that the email and its attachments are actually virus free. This is in keeping with good computing practice.

**Comment by jensroes** [comment]
I meant updates of dependencies (or my lack thereof), not `psyntur`.

I'm getting this:

```r
> library(psyntur)
> describe_across(faithfulfaces, 
+                 variables = c(trustworthy, faithful), 
+                 functions = list(avg = mean, stdev = sd), 
+                 by = face_sex)
Error:
! Problem with `summarise()` input `..1`.
ℹ `..1 = across(c(trustworthy, faithful), functions)`.
x Can't convert `fn`, a number, to a function.
ℹ The error occurred in group 1: face_sex = "female".
Run `rlang::last_error()` to see where the error occurred.
```

but not when using quotes

```r
> describe_across(faithfulfaces, 
+                 variables = c(trustworthy, faithful), 
+                 functions = list(avg = "mean", stdev = "sd"), 
+                 by = face_sex)
# A tibble: 2 × 5
  face_sex trustworthy_avg trustworthy_stdev faithful_avg faithful_stdev
  <chr>              <dbl>             <dbl>        <dbl>          <dbl>
1 female              4.44             0.742         5.55          0.802
2 male                4.21             0.822         4.75          0.932
```

**Comment by mark-andrews** [comment]
In your error message,
```r
! Problem with `summarise()` input `..1`.
ℹ `..1 = across(c(trustworthy, faithful), functions)`.
x Can't convert `fn`, a number, to a function.
ℹ The error occurred in group 1: face_sex = "female".
```
it say `fn` is a number. Did you accidentally assign `mean` and/or `sd` to numbers? E.g. `mean <- 42`.

**Comment by jensroes** [comment]
My god! Yes "mean" does exist as a number in my environment. I didn't worry about that at all R is usually great at not confusing functions and other objects :)

**Comment by mark-andrews** [comment]
In that case, I think we can safely say we solved this "problem".
